cli:
  - changed-files:
      - any-glob-to-any-file:
          - "Bison.CLI/**"

database:
  - changed-files:
      - any-glob-to-any-file:
          - "SimpleDB/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
