// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bison.Razor.Migrations
{
    [DbContext(typeof(BisonDBContext))]
    [Migration("20261002110215_InitialBisonDBSchema")]
    partial class InitialBisonDBSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.Property<int>("TaxonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentTaxonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VernacularName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("dwc_TaxonID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaxonId");

                    b.HasIndex("ParentTaxonId");

                    b.ToTable("Taxons");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.HasOne("Taxon", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTaxonId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Taxon", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
